### ISSUE TITLE
Bug in Readme example?

### ISSUE THREAD

**Issue by hatton** [megahertz/electron-call#1]
First-- this is the library I've been waiting for since `remote` started getting deprecated -- thanks!

However, I feel pretty dumb at the moment because I haven't been able to get it to work at all. 

As I look at the instructions in the readme, I wonder, how does renderer → main even work? The sample code shows only the types being loaded from `mainApi.ts`. Some other code must have to import that file somewhere else, or the call to `provide()` will never be called. OK, so the instructions don't mention it, but logically this would be somewhere in the main process. So I add

`import "./MainApi"` to my main.ts, which is the entry point to the main process. Now in a main-process debugger, I set a breakpoint and see it call

`call.provide("MainApi", MainApi);`

So far, so good. Now in the browser debugger, I see that it is executing `console.log(await mainApi.getAppName());`, but nothing comes out. The call to `getAppName()` just never returns. Meanwhile, in the main debugger, I can see the function `getAppName()` is never executed.

electron-call: 0.0.7
electron: 15.5.7

Any ideas for me would be much appreciated. Or perhaps you have a sample repo that uses this?

**Comment by hatton** [comment]
I did more debugging into the library itself, and it appears that the readme is in error. In `IpcFacade.js`, we have

`const methods = getObjectMethods(apiInstance, options);`

But we don't have an instance, we only have a class. So `methods` gets `[]`.

So, if instead of

`call.provide('MainApi', MainApi);`

I do 

`call.provide('MainApi', new MainApi());`

then the sample works.

**Comment by hatton** [comment]
Here's what I ended up with, in case it helps someone else:

MainProcessApi.ts:

```
import { app } from "electron";
import call from "electron-call";

export class MainProcessApi {
  async getAppName() {
    return app.getName();
  }
}

const mainProcessInstance = new MainProcessApi();
call.provide("MainProcessApi", mainProcessInstance);
```

MainProcessApiAccess.ts:

```
// This file should be loaded into the render process
import call from "electron-call";
// notice, we're importing type info only. The code won't be loaded in the render process, won't be available in browser debugger
import type { MainProcessApi } from "./MainProcessApi";

const wrapper = call.use<MainProcessApi>("MainProcessApi");

export default wrapper;

```

In the `main.ts`
```
import "./MainProcessApi"; // this instantiates the API for our render process to call
```

Anywhere in the render code:
```
import main from "../MainProcessApiAccess";

 main.getAppName().then((r) => console.log(r));

```

**Comment by megahertz** [comment]
Yes, the sample was incorrect, thank you
